// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdZ4yH56GYBNKk2F3Io2j3q5dah8-93Vg',
    appId: '1:802084366872:web:e1ca6e66897d1851f9716d',
    messagingSenderId: '802084366872',
    projectId: 'book-reader-app-ff47f',
    authDomain: 'book-reader-app-ff47f.firebaseapp.com',
    storageBucket: 'book-reader-app-ff47f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFoIFJ4rOA0c209lvSf4NTBc-UKP1anlg',
    appId: '1:802084366872:android:d8157e2b63da866af9716d',
    messagingSenderId: '802084366872',
    projectId: 'book-reader-app-ff47f',
    storageBucket: 'book-reader-app-ff47f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADOHRn-WYx01fQ_c3DAjsYy96u6YtftVc',
    appId: '1:802084366872:ios:e60609a709e0a815f9716d',
    messagingSenderId: '802084366872',
    projectId: 'book-reader-app-ff47f',
    storageBucket: 'book-reader-app-ff47f.firebasestorage.app',
    iosBundleId: 'com.example.readerTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADOHRn-WYx01fQ_c3DAjsYy96u6YtftVc',
    appId: '1:802084366872:ios:e60609a709e0a815f9716d',
    messagingSenderId: '802084366872',
    projectId: 'book-reader-app-ff47f',
    storageBucket: 'book-reader-app-ff47f.firebasestorage.app',
    iosBundleId: 'com.example.readerTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdZ4yH56GYBNKk2F3Io2j3q5dah8-93Vg',
    appId: '1:802084366872:web:bbdd3042301025b7f9716d',
    messagingSenderId: '802084366872',
    projectId: 'book-reader-app-ff47f',
    authDomain: 'book-reader-app-ff47f.firebaseapp.com',
    storageBucket: 'book-reader-app-ff47f.firebasestorage.app',
  );
}
